name: Web Deploy to IPFS

on:
  pull_request:
    branches:
      - dev
    paths:
      - apps/web/**
      - packages/**
      - .github/workflows/web-deploy-ipfs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs: # This exposes the CID output of the action to the rest of the workflow
      cid: ${{ steps.deploy.outputs.cid }}

    permissions:
      pull-requests: write
      id-token: write

    name: Deploy to IPFS

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/yarn

      - uses: ./.github/actions/build
        with:
          secrets: ${{ toJSON(secrets) }}
          prod: ${{ true }}

      - name: Set unique output directory name
        run: echo "OUT_DIR=out-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Rename out directory with timestamp
        run: mv ./apps/web/out ./apps/web/$OUT_DIR

      - name: Remove .html extension from all files
        run: |
          for file in $(find ./apps/web/$OUT_DIR -name '*.html' | sed 's|^\./||'); do
            cp ${file%} ${file%.*}
          done

      - uses: ipfs/ipfs-deploy-action@v1
        name: Deploy to IPFS
        id: deploy
        # TODO: remove this
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          path-to-deploy: ./apps/web/${{ env.OUT_DIR }}
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          pinata-jwt-token: ${{ secrets.PINATA_JWT_TOKEN }}
          pinata-pinning-url: "https://api.pinata.cloud/psa" # DEFAULT
          set-github-status: "true" # DEFAULT
          upload-car-artifact: "true" # DEFAULT
          github-token: ${{ github.token }} 
          pin-name: ${{ env.OUT_DIR }} # if not set, default to {repo-name}-{commit-sha-short}

      - run: echo  "IPFS_CID=${{ steps.deploy.outputs.cid }}" >> $GITHUB_ENV

      # - name: Deploy to IPFS
      #   id: deploy
      #   uses: aquiladev/ipfs-action@v0.2.1
      #   with:
      #     path: apps/web/${{ env.OUT_DIR }}
      #     pinName: ${{ env.OUT_DIR }}
      #     service: pinata
      #     pinataKey: ${{ secrets.PINATA_API_KEY }}
      #     pinataSecret: ${{ secrets.PINATA_SECRET_KEY }}

      # - run: echo  "IPFS_CID=${{ steps.deploy.outputs.Hash }}" >> $GITHUB_ENV

      - name: Output IPFS CID
        run: |
          echo "Deployed IPFS CID: ${{ env.IPFS_CID }}"
          echo "Gateway link: https://${{ env.IPFS_CID }}.ipfs.dweb.link/"
